on:
  schedule:
    - cron: '5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo repository name
        run: echo "${{ github.repository }}"

      - name: repository checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.KEY }}
          path: Study_Oracle

      - name: Add date and push
        run: |
          cd Study_Oracle
          date >> date.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "TEST"
          git push
