on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout
        uses: actions/checkout@v3
        with:
          repository: youngmoon525/Study_Oracle
          token: ${{ secrets.KEY }}
          path: Study_Oracle

      - name: Add date and push
        run: |
          date > generated.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -m "test"
          git push
